version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sweetbyte

    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

    goos:
      - linux
      - windows
      - darwin
      - freebsd

    goarch:
      - amd64
      - arm64
      - 386

archives:
  - formats: [tar.gz]

    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      
    format_overrides:
      - goos: windows
        formats: zip

changelog:
  # Sort commits by date (asc or desc)
  sort: asc
  
  # Use GitHub for changelog generation
  use: github
  
  # Group commits by type for better organization
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Tests'
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: 'Documentation updates'
      regexp: '^.*?docs?(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: 'Build process updates'
      regexp: '^.*?(build|ci)(\([[:word:]]+\))??!?:.+$'
      order: 6
    - title: Others
      order: 999

  filters:
    # Exclude commits that match these patterns
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^ci:"
      - "^build:"
      - "^revert:"
      - "^Merge pull request"
      - "^Merge branch"
      - "typo"
      - "^minor"
      - "^bump"
      - "^update dependencies"
      - "^update.*version"
      - "^release"
      - "^prepare"
      - "^[Uu]pdate README"

    # Include only commits that match these patterns (optional)
    # include:
    #   - "^feat:"
    #   - "^fix:"
    #   - "^perf:"